ame: tests
on:
  pull_request:

jobs:
  python-tests-pr:
    name: python
    if: github.event.pull_request.merged != true
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout Haarpy
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        shell: bash
        run: |
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
          pip install pytest-cov wheel codecov

      - name: Install Haarpy
        run: |
          pip install -e .

      - name: Run tests
        run: python3 -m pytest haarpy --cov=haarpy --cov-report term-missing --cov-report=html:coverage_html_report --cov-report=xml:coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          disable_search: true
          fail_ci_if_error: true